version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: user-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - userapi-net

volumes:
  mysql_data:

networks:
  userapi-net:
    driver: bridge
